version: "3.8"
services:
  app:
    build: . 
    volumes:
      - .:/DRF
    ports:
      - "8000:8000"
    image: app:DRF
    container_name: DRF_container
    command: python manage.py runserver 0.0.0.0:8000
